i dont like the allowance pattern, do you?
require one more tx
and is dangerous (defi saver hack)
why not use a transfer function with callback

pseudo code:
contract ERC20-Kill-Allowance {
	function transfer(dapp, value, calldata) {
		require(dapp != this);
		transfer(dapp, value);
		dapp.call(calldata);
	}
}

calldata is generated by dapp the sender is using
not any more riskier than allowance pattern
